# Generated by Django 5.1 on 2024-08-22 13:07

import commerce_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Supplier', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Unit_Of_Measure', models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Bag', 'Bag'), ('Pcs', 'Pcs'), ('Pcs', 'Pc'), ('Carton', 'Carton'), ('Pkt', 'Pkt'), ('Tons', 'Tons'), ('Bottles', 'Bottles'), ('Dose', 'Dose'), ('Course', 'Course'), ('Square Meter', 'Square Meter'), ('Case', 'Case'), ('Custom Software', 'Custom Software')], db_index=True, max_length=255, null=True)),
                ('price_ksh', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('Duration', models.CharField(db_index=True, max_length=255, null=True)),
                ('Price_Negotiable', models.CharField(db_index=True, max_length=255, null=True)),
                ('Item_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, db_index=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('about_Image', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=(('default', 'Select availability...'), ('available', 'Available now'), ('Service available', ' Service Available now'), ('Course available', 'Course available'), ('Out of Stock', 'Out of Stock'), ('future', commerce_app.models.ItemImage.availability_description)), db_index=True, max_length=255, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.item')),
                ('categories', models.ManyToManyField(blank=True, related_name='images', to='commerce_app.category')),
            ],
        ),
    ]
