# Generated by Django 5.1 on 2024-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('news', 'News'), ('advertisement', 'Advertisement'), ('video', 'Video Upload'), ('Update', 'Update')], max_length=20),
        ),
    ]
