# Generated by Django 5.1 on 2024-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0004_alter_announcement_announcement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarerequest',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='preferred_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwarerequest',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='softwarerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='softwarerequest',
            name='target_customers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
