# Generated by Django 5.1 on 2024-08-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0008_learningmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningMaterial',
        ),
    ]
