# Generated by Django 5.1 on 2024-08-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0010_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
    ]
