# Generated by Django 5.1 on 2024-08-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce_app", "0013_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="course",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studentprogress",
            name="current_module",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="QuizResult",
        ),
    ]
