# Generated by Django 5.1 on 2024-08-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce_app",
            "0015_studentprogress_module_completed_assignment_exam_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="commerce_app.exam",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="max_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
