# Generated by Django 5.1 on 2024-08-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce_app", "0016_remove_question_quiz_question_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="commerce_app.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(),
        ),
    ]
