# Generated by Django 5.1 on 2024-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce_app", "0017_question_quiz_alter_question_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
