# Generated by Django 5.1 on 2024-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0019_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
