# Generated by Django 5.1 on 2024-11-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0020_submission_graded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogress',
            old_name='module_completed',
            new_name='modules_completed',
        ),
    ]
