# Generated by Django 5.1 on 2024-11-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0021_rename_module_completed_studentprogress_modules_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
