# Generated by Django 5.1 on 2024-11-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0022_remove_course_status_assignment_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='modules_completed',
        ),
    ]
