# Generated by Django 5.1 on 2024-11-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0023_remove_studentprogress_modules_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='modules_completed',
            field=models.IntegerField(default=0),
        ),
    ]
