# Generated by Django 5.1 on 2024-11-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0025_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(upload_to='cover_letters/'),
        ),
    ]
