# Generated by Django 5.1 on 2024-11-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0026_alter_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(),
        ),
    ]
