# Generated by Django 5.1 on 2024-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0030_cyber_service_cyber_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyber_service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cyber_services/'),
        ),
    ]
