# Generated by Django 5.1 on 2025-01-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0032_remove_cyber_service_duration_cyber_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letter/'),
        ),
    ]
