# Generated by Django 5.1 on 2025-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0033_alter_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
