# Generated by Django 5.1 on 2025-04-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0035_contact_alter_department_contact_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.IntegerField(default=0)),
                ('battery_level', models.IntegerField(default=100)),
                ('working_hours_limit', models.IntegerField(default=8)),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
    ]
