# Generated by Django 5.1 on 2025-04-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0036_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payroll_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
