# Generated by Django 5.1 on 2025-04-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0037_loanrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
