# Generated by Django 5.1 on 2025-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0038_remove_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='is_alive',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='robot',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='model_name',
            field=models.CharField(choices=[('A1', 'Alpha-1'), ('B2', 'Beta-2'), ('X9', 'Xenon-9')], default='A1', max_length=10),
        ),
    ]
