# Generated by Django 5.1 on 2025-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0043_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answers',
            field=models.JSONField(blank=True, default=list, help_text='Provide incorrect answers as a list of strings', null=True),
        ),
    ]
