# Generated by Django 5.1 on 2026-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0046_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
