# Generated by Django 5.1 on 2026-01-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0047_exam_exam_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_password',
            new_name='access_password',
        ),
    ]
