# Generated by Django 5.1 on 2026-01-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0049_service_remove_order_item_image_remove_order_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Item_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce_app.itemimage')),
                ('items', models.ManyToManyField(to='commerce_app.cartitem')),
            ],
        ),
    ]
